version: "3.9"

services:
  microservice-locations-create:
    build: ./microservice-locations-create
    ports:
      - "4003:4003"
    networks:
      - provinces-locations-network
    environment:
      - DB_HOST_L_P=${DB_HOST_L_P}
      - DB_USER=${DB_USER_L_P}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME_L_P=${DB_NAME_L_P}
      - DB_PORT=3306
      - RABBITMQ_URL=${RABBITMQ_URL}

  microservice-locations-get:
    build: ./microservice-locations-get
    ports:
      - "4002:4002"
    networks:
      - provinces-locations-network
    environment:
      - DB_HOST_L_P=${DB_HOST_L_P}
      - DB_USER=${DB_USER_L_P}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME_L_P=${DB_NAME_L_P}
      - DB_PORT=3306
      - RABBITMQ_URL=${RABBITMQ_URL}

  microservice-locations-delete:
    build: ./microservice-locations-delete
    networks:
      - provinces-locations-network
    environment:
      - DB_HOST_L_P=${DB_HOST_L_P}
      - DB_USER=${DB_USER_L_P}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME_L_P=${DB_NAME_L_P}
      - DB_PORT=3306
      - RABBITMQ_URL=${RABBITMQ_URL}

  microservice-provinces-get:
    build: ./microservice-provinces-get
    ports:
      - "4001:4001"
    networks:
      - provinces-locations-network
    environment:
      - DB_HOST_L_P=${DB_HOST_L_P}
      - DB_USER=${DB_USER_L_P}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME_L_P=${DB_NAME_L_P}
      - DB_PORT=3306
      - RABBITMQ_URL=${RABBITMQ_URL}

  microservice-provinces-delete:
    build: ./microservice-provinces-delete
    ports:
      - "4000:4000"
    networks:
      - provinces-locations-network
    environment:
      - DB_HOST_L_P=${DB_HOST_L_P}
      - DB_USER=${DB_USER_L_P}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME_L_P=${DB_NAME_L_P}
      - DB_PORT=3306
      - RABBITMQ_URL=${RABBITMQ_URL}

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - provinces-locations-network
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

networks:
  provinces-locations-network:
    driver: bridge
